### PR TITLE
Add removeTodo, line throught items and more

### PR DESCRIPTION
**Pull request by soonsam123**
If this pull request is accepted, it will add the following functionality.
1. A line through the items when they are completed;
2. A way to add a new item by simply pressing the return key, instead of moving your finger to the add button;
3. It will be not able to enter an empty todo;
4. A way to remove todo by using swipe to dismiss.

### CODE REVIEW

**Comment by lesnitsky** [comment]
Wow, good job! Did you use git-tutor?

**Comment by soonsam123** [comment]
I didn't know about that, I am searched about it now. I am gonna read it.
I just followed your previous code.
Thank you!

**Comment by soonsam123** [comment]
Do I need to change something in the commit?

**Comment by lesnitsky** [comment]
since the repo uses git-tutor, all changes should also be done using it.
Check out git-tutor branch to see commit history.

**Comment by lesnitsky** [comment]
@soonsam123 since this PR requires rework with git-tutor, closing this for now.

**Pull request closed without merging**
